Reverts the test suite's kubectl because apply failed with:
error: unable to recognize "/var/lib/rancher/k3s/server/manifests/ystack-10-minio.yaml": no matches for kind "StatefulSet" in version "apps/v1"